/* eslint-disable @typescript-eslint/no-explicit-any */

// app/api/generate-comments/route.ts
// ═══════════════════════════════════════════════════════════════
// AI REPORT CARD COMMENTS GENERATOR - FIRST TERM
// Focus: Welcome, initial assessment, foundation building
// No promotion talk (that comes at end of year)
// ═══════════════════════════════════════════════════════════════

import { NextRequest, NextResponse } from 'next/server'

export async function POST(req: NextRequest) {
  try {
    const { studentName, averageScore, subjects, className, gender } = await req.json()

    // ─── Performance Level Detection ────────────────────────────
    const getPerformanceLevel = (score: number) => {
      if (score >= 90) return 'outstanding'
      if (score >= 85) return 'excellent'
      if (score >= 80) return 'veryGood'
      if (score >= 75) return 'good'
      if (score >= 70) return 'aboveAverage'
      if (score >= 65) return 'satisfactory'
      if (score >= 60) return 'average'
      if (score >= 55) return 'belowAverage'
      if (score >= 50) return 'marginal'
      if (score >= 45) return 'poor'
      return 'veryPoor'
    }

    const performanceLevel = getPerformanceLevel(averageScore)
    const pronoun = gender?.toLowerCase() === 'female' ? 'She' : 'He'
    const possessive = gender?.toLowerCase() === 'female' ? 'her' : 'his'
    const objective = gender?.toLowerCase() === 'female' ? 'her' : 'him'

    const bestSubject = subjects.length > 0
      ? subjects.reduce((a: any, b: any) => a.score > b.score ? a : b)
      : { name: 'various subjects', score: 0 }

    const weakestSubject = subjects.length > 0
      ? subjects.reduce((a: any, b: any) => a.score < b.score ? a : b)
      : { name: 'some subjects', score: 0 }

    const ctx: CommentContext = {
      studentName,
      averageScore,
      className,
      pronoun,
      possessive,
      objective,
      bestSubject,
      weakestSubject,
    }

    // Get random templates for teacher and principal
    const teacherTemplates = TEACHER_COMMENTS[performanceLevel] || TEACHER_COMMENTS.average
    const principalTemplates = PRINCIPAL_COMMENTS[performanceLevel] || PRINCIPAL_COMMENTS.average

    const teacherComment = interpolate(
      teacherTemplates[Math.floor(Math.random() * teacherTemplates.length)],
      ctx
    )

    const principalComment = interpolate(
      principalTemplates[Math.floor(Math.random() * principalTemplates.length)],
      ctx
    )

    return NextResponse.json({
      teacher_comment: teacherComment,
      principal_comment: principalComment,
      performance_level: performanceLevel,
    })
  } catch (error) {
    console.error('Error generating comments:', error)
    return NextResponse.json(
      { error: 'Failed to generate comments' },
      { status: 500 }
    )
  }
}

// ─── Types & Helpers ─────────────────────────────────────────────
interface CommentContext {
  studentName: string
  averageScore: number
  className: string
  pronoun: string
  possessive: string
  objective: string
  bestSubject: { name: string; score: number }
  weakestSubject: { name: string; score: number }
}

function interpolate(template: string, ctx: CommentContext): string {
  return template
    .replace(/\{studentName\}/g, ctx.studentName)
    .replace(/\{averageScore\}/g, ctx.averageScore.toString())
    .replace(/\{className\}/g, ctx.className)
    .replace(/\{pronoun\}/g, ctx.pronoun)
    .replace(/\{possessive\}/g, ctx.possessive)
    .replace(/\{objective\}/g, ctx.objective)
    .replace(/\{bestSubject\}/g, ctx.bestSubject.name)
    .replace(/\{bestScore\}/g, ctx.bestSubject.score.toString())
    .replace(/\{weakestSubject\}/g, ctx.weakestSubject.name)
    .replace(/\{weakestScore\}/g, ctx.weakestSubject.score.toString())
}

// ═══════════════════════════════════════════════════════════════
// TEACHER COMMENTS — Focused on First Term Foundation
// ═══════════════════════════════════════════════════════════════
const TEACHER_COMMENTS: Record<string, string[]> = {
  outstanding: [
    `{studentName} has begun the academic year on an exceptional note, achieving an outstanding {averageScore}% average this term. {pronoun} has shown remarkable adjustment to new class expectations, particularly excelling in {bestSubject} ({bestScore}%). {pronoun} sets a wonderful example for {possessive} peers.`,
    `An exceptional start by {studentName}! With {averageScore}% average, {pronoun} has demonstrated intellectual maturity and enthusiasm for learning. {possessive} mastery of {bestSubject} ({bestScore}%) is impressive. {pronoun} is encouraged to sustain this excellent foundation.`,
    `{studentName} has laid an outstanding foundation with a {averageScore}% average. {pronoun} adapted quickly to new topics and showed remarkable understanding across all subjects, especially {bestSubject} ({bestScore}%). This strong start bodes well for continued success.`,
    `Truly exceptional performance! {studentName} achieved {averageScore}% average, showing {pronoun.toLowerCase()} is more than capable of the academic demands. {possessive} {bestScore}% in {bestSubject} highlights {possessive} strengths.`,
    `{studentName} has made an outstanding debut with {averageScore}% average. {possessive} enthusiasm, discipline, and academic ability are all evident. {bestSubject} ({bestScore}%) is a particular strength. Keep up the excellent work!`,
    `Brilliant results, {studentName}! With {averageScore}% average, {pronoun} has set a high standard. {possessive} strong grasp of {bestSubject} ({bestScore}%) demonstrates {possessive} readiness for more advanced concepts.`,
    `{studentName} has shown outstanding academic capability from day one, averaging {averageScore}%. {possessive} performance in {bestSubject} ({bestScore}%) is exemplary. {pronoun} is on an excellent trajectory.`,
    `Exceptional work! {studentName} earned {averageScore}% average, showing {pronoun.toLowerCase()} has fully embraced the academic year. {possessive} focus in {bestSubject} ({bestScore}%) is admirable.`,
    `{studentName} has demonstrated outstanding scholarly ability with {averageScore}% average. {possessive} {bestScore}% in {bestSubject} reflects deep understanding. {pronoun} is on an excellent path.`,
    `Superb start, {studentName}! {averageScore}% average shows {pronoun.toLowerCase()} takes {possessive} studies seriously. Continue building on {possessive} strength in {bestSubject}.`,
    `{studentName} has shown outstanding potential with {averageScore}% average. A stellar {bestScore}% in {bestSubject} — this is the standard to maintain.`,
    `Remarkable work, {studentName}! With {averageScore}% average, {pronoun} has proven {possessive} academic maturity. {possessive} best showing was in {bestSubject} ({bestScore}%). Sustain this!`,
    `{studentName} has begun the year with outstanding {averageScore}% average. {possessive} {bestScore}% in {bestSubject} is particularly praiseworthy. Consistency will bring exceptional results.`,
    `Excellent effort, {studentName}! {averageScore}% average shows {pronoun.toLowerCase()} settled into the class beautifully. Continue exploring {possessive} strength in {bestSubject}.`,
    `{studentName} has performed outstandingly with {averageScore}% average. {possessive} clear grasp of {bestSubject} ({bestScore}%) will serve {objective} well.`,
    `Top-notch work! {studentName} earned {averageScore}% average, an impressive foundation. {possessive} {bestScore}% in {bestSubject} is commendable. Ready for greater challenges ahead.`,
    `{studentName} started the year on an outstanding note with {averageScore}% average. Consistency in {bestSubject} ({bestScore}%) is impressive. {pronoun} is set up for a wonderful year.`,
    `Exceptional performance, {studentName}! {averageScore}% average is a strong start. {possessive} {bestScore}% in {bestSubject} shines. Keep this pace up.`,
    `{studentName} has shown outstanding academic engagement with {averageScore}% average and {bestScore}% in {bestSubject} — a wonderful foundation for the year ahead.`,
    `Brilliant introduction to the year! {studentName} achieved {averageScore}% average. {possessive} {bestScore}% in {bestSubject} stands out. Sustain this excellence!`,
    `{studentName} has begun the year with exceptional focus, earning {averageScore}% average. {possessive} performance in {bestSubject} ({bestScore}%) reflects deep engagement. Well done!`,
    `Outstanding effort, {studentName}! {averageScore}% average with a superb {bestScore}% in {bestSubject}. {pronoun} is well-prepared for continued success.`,
    `{studentName} has proved {possessive} academic strength with {averageScore}% average. {possessive} best subject, {bestSubject} ({bestScore}%), is particularly strong.`,
    `Superb academic display! {studentName} earned {averageScore}% average. {possessive} {bestScore}% in {bestSubject} is a real highlight. Continue this trajectory.`,
    `{studentName} has laid an exceptional academic foundation with {averageScore}% average. Keep building on {possessive} strengths.`,
    `Outstanding work by {studentName}! {averageScore}% average and {bestScore}% in {bestSubject} — a fantastic beginning to the academic year.`,
    `{studentName} has demonstrated outstanding intellectual capacity with {averageScore}% average. {possessive} strong showing in {bestSubject} sets a wonderful tone.`,
    `Exceptional academic display! {studentName} earned {averageScore}% average. {possessive} {bestScore}% in {bestSubject} is commendable. Continue shining!`,
    `{studentName} started the academic year outstandingly with {averageScore}% average. {possessive} performance in {bestSubject} ({bestScore}%) is exemplary.`,
    `Wonderful work, {studentName}! {averageScore}% average shows dedication and ability. Sustain this momentum.`,
    `{studentName} has performed with outstanding excellence with {averageScore}% average and {bestScore}% in {bestSubject} — a fantastic foundation.`,
  ],

  excellent: [
    `{studentName} has made an excellent start to the academic year, achieving {averageScore}% average. {pronoun} demonstrates strong understanding across the curriculum, with {bestSubject} being a particular strength ({bestScore}%). Well done!`,
    `Excellent work, {studentName}! With {averageScore}% average, {pronoun} has shown consistent effort in {possessive} studies. {possessive} {bestScore}% in {bestSubject} reflects {possessive} ability. Keep it up!`,
    `{studentName} has produced excellent results, averaging {averageScore}%. {pronoun} excels particularly in {bestSubject} ({bestScore}%). This strong performance shows great potential.`,
    `Very impressive performance by {studentName}! {averageScore}% average is commendable. {possessive} standout performance in {bestSubject} ({bestScore}%) is a highlight to build on.`,
    `{studentName} has shown excellent understanding of the topics with {averageScore}% average. {possessive} {bestScore}% in {bestSubject} is impressive. Keep striving!`,
    `Excellent effort, {studentName}! With {averageScore}% average, {pronoun} has shown strong academic ability. {bestSubject} ({bestScore}%) is a clear strength.`,
    `{studentName} has performed excellently, achieving {averageScore}% average. {possessive} performance in {bestSubject} ({bestScore}%) stands out. A great foundation!`,
    `Very good results, {studentName}! {pronoun} earned an excellent {averageScore}% average. {bestSubject} ({bestScore}%) is {possessive} strongest subject.`,
    `{studentName} has shown remarkable consistency, earning an excellent {averageScore}% average. {possessive} {bestScore}% in {bestSubject} is noteworthy.`,
    `Excellent display, {studentName}! With {averageScore}% average and {bestScore}% in {bestSubject}, {pronoun} has established a strong platform for growth.`,
    `{studentName} has performed excellently across all subjects, averaging {averageScore}%. {possessive} strength in {bestSubject} ({bestScore}%) is commendable.`,
    `Very good work, {studentName}! {pronoun} has achieved an excellent {averageScore}% average, demonstrating strong understanding.`,
    `{studentName} has shown consistent excellence with {averageScore}% average. {possessive} {bestScore}% in {bestSubject} is a highlight.`,
    `Excellent progress, {studentName}! With {averageScore}% average, {pronoun} has shown what focused effort can achieve.`,
    `{studentName} has delivered an excellent performance, averaging {averageScore}%. Keep up this wonderful momentum!`,
    `Very impressive, {studentName}! {pronoun} has earned an excellent {averageScore}% average, with {bestSubject} as a particular strength at {bestScore}%.`,
    `{studentName} has shown excellent academic ability, achieving {averageScore}% average. {possessive} performance in {bestSubject} is commendable.`,
    `Excellent results, {studentName}! With {averageScore}% average, {pronoun} has proven {possessive} capability. {bestSubject} ({bestScore}%) stands out.`,
    `{studentName} has performed excellently, earning {averageScore}% average. {possessive} {bestScore}% in {bestSubject} reflects {possessive} dedication.`,
    `Very good effort, {studentName}! {pronoun} has achieved an excellent {averageScore}% average. Well done!`,
    `{studentName} has demonstrated excellent understanding across subjects with {averageScore}% average. {bestSubject} ({bestScore}%) is a strength.`,
    `Excellent academic performance, {studentName}! With {averageScore}% average, {pronoun} has made us proud.`,
    `{studentName} has shown excellence in {possessive} studies with {averageScore}% average. {bestSubject} ({bestScore}%) is particularly impressive.`,
    `Very good work, {studentName}! {pronoun} has earned an excellent {averageScore}% average, demonstrating strong academic potential.`,
    `{studentName} has performed excellently, achieving {averageScore}% average. Keep striving for greatness!`,
    `Excellent results, {studentName}! With {averageScore}% average, {pronoun} has shown what dedication can achieve.`,
    `{studentName} has demonstrated excellent academic ability with {averageScore}% average. {possessive} future is bright.`,
    `Very impressive, {studentName}! {pronoun} has achieved an excellent {averageScore}% average, showing consistent high performance.`,
    `{studentName} has excelled with an excellent average of {averageScore}%. {bestSubject} ({bestScore}%) is a highlight.`,
    `Excellent work, {studentName}! With {averageScore}% average, {pronoun} has shown what focused students can achieve.`,
    `{studentName} has performed admirably with an excellent average of {averageScore}%. Keep up the good work!`,
  ],

  veryGood: [
    `{studentName} has performed very well this term with {averageScore}% average. {pronoun} shows good understanding across the curriculum, particularly in {bestSubject} ({bestScore}%). Continued focus on {weakestSubject} will help {objective} reach even greater heights.`,
    `Very good effort, {studentName}! With {averageScore}% average, {pronoun} has demonstrated solid academic progress. {bestSubject} remains {possessive} strongest subject at {bestScore}%. Building on {possessive} strengths in {weakestSubject} will elevate overall performance.`,
    `{studentName} has shown consistent progress, achieving a very good {averageScore}% average. {possessive} performance in {bestSubject} ({bestScore}%) is impressive. With continued dedication in {weakestSubject}, even greater success awaits.`,
    `Commendable progress! {studentName} has maintained a very good {averageScore}% average. {pronoun} excels in {bestSubject} ({bestScore}%) and is encouraged to apply similar successful strategies to strengthen {weakestSubject}.`,
    `{studentName} has achieved a solid very good {averageScore}% average. {possessive} strength in {bestSubject} ({bestScore}%) is evident. Focused practice in {weakestSubject} will yield excellent results.`,
    `Very good performance, {studentName}! With {averageScore}% average, {pronoun} has shown strong understanding. {bestSubject} ({bestScore}%) is a highlight worth celebrating.`,
    `{studentName} has performed very well, earning {averageScore}% average. {possessive} {bestScore}% in {bestSubject} is impressive. Continued attention to {weakestSubject} will unlock even more potential.`,
    `Great progress, {studentName}! {pronoun} has achieved a very good {averageScore}% average. {bestSubject} ({bestScore}%) is a clear strength to build upon.`,
    `{studentName} has shown very good understanding with {averageScore}% average. {possessive} performance in {bestSubject} stands out at {bestScore}%. Keep this momentum going!`,
    `Very good effort, {studentName}! With {averageScore}% average, {pronoun} is on an excellent trajectory. {bestSubject} ({bestScore}%) reflects {possessive} capability.`,
    `{studentName} has delivered a very good performance, averaging {averageScore}%. {possessive} {bestScore}% in {bestSubject} shows great potential for further growth.`,
    `Excellent work, {studentName}! {pronoun} has achieved a very good {averageScore}% average. Keep pushing toward excellence.`,
    `{studentName} has shown very good academic ability with {averageScore}% average. {bestSubject} ({bestScore}%) is a clear strength that can inspire growth in other areas.`,
    `Very good results, {studentName}! With {averageScore}% average, {pronoun} has demonstrated solid understanding. {bestSubject} ({bestScore}%) is noteworthy.`,
    `{studentName} has performed very well, earning {averageScore}% average. {possessive} performance in {bestSubject} is truly commendable.`,
    `Great effort, {studentName}! {pronoun} has achieved a very good {averageScore}% average. Keep building on this strong foundation.`,
    `{studentName} has shown very good progress with {averageScore}% average. {bestSubject} ({bestScore}%) is a highlight of {possessive} academic journey.`,
    `Very good performance, {studentName}! With {averageScore}% average, {pronoun} has made us proud. Continue this excellent work.`,
    `{studentName} has achieved a very good {averageScore}% average. {possessive} strength in {bestSubject} is evident and inspiring.`,
    `Great results, {studentName}! {pronoun} has earned a very good {averageScore}% average. {bestSubject} ({bestScore}%) stands out beautifully.`,
    `{studentName} has shown very good understanding, averaging {averageScore}%. {possessive} {bestScore}% in {bestSubject} is genuinely impressive.`,
    `Very good work, {studentName}! With {averageScore}% average, {pronoun} has demonstrated solid academic progress worth celebrating.`,
    `{studentName} has performed very well, achieving {averageScore}% average. Keep up this wonderful work!`,
    `Very good effort, {studentName}! {pronoun} has earned {averageScore}% average, showing good understanding across subjects.`,
    `{studentName} has shown very good academic ability with {averageScore}% average. {bestSubject} ({bestScore}%) is a genuine strength.`,
    `Great progress, {studentName}! With {averageScore}% average, {pronoun} is well on the path to excellence.`,
    `{studentName} has achieved a very good {averageScore}% average. Well done and keep going!`,
    `Very good performance, {studentName}! {pronoun} has shown consistent effort and strong understanding.`,
    `{studentName} has demonstrated very good academic skills with {averageScore}% average. Keep striving for the top!`,
    `Great work, {studentName}! With {averageScore}% average, {pronoun} has made commendable progress.`,
    `{studentName} has performed very well, earning {averageScore}% average. {bestSubject} ({bestScore}%) is truly impressive.`,
  ],

  good: [
    `{studentName} has achieved a good {averageScore}% average this term. {pronoun} shows strength in {bestSubject} ({bestScore}%). Consistent revision and dedicated focus on {weakestSubject} will further enhance {possessive} academic performance.`,
    `Good effort, {studentName}! With {averageScore}% average, {pronoun} has met the expected learning outcomes. {possessive} best performance was in {bestSubject} ({bestScore}%). Building consistency in {weakestSubject} will bring greater rewards.`,
    `{studentName} has performed commendably with {averageScore}% average. {bestSubject} ({bestScore}%) is {possessive} strongest area. Applying the same dedication to {weakestSubject} will yield excellent improvements.`,
    `Well done, {studentName}. {pronoun} has achieved a good {averageScore}% average. {possessive} performance in {bestSubject} ({bestScore}%) is commendable. With continued focus on {weakestSubject}, {pronoun} can reach new heights.`,
    `{studentName} has shown good understanding with {averageScore}% average. {possessive} {bestScore}% in {bestSubject} is impressive. Focused study in {weakestSubject} will make a positive difference.`,
    `Good performance, {studentName}! With {averageScore}% average, {pronoun} has met expectations. {bestSubject} ({bestScore}%) is a real strength to celebrate.`,
    `{studentName} has achieved a good {averageScore}% average. {possessive} performance in {bestSubject} stands out at {bestScore}%. Keep building on this!`,
    `Commendable effort, {studentName}! {pronoun} has earned {averageScore}% average, showing good grasp of key concepts.`,
    `{studentName} has performed well, achieving {averageScore}% average. {bestSubject} ({bestScore}%) is {possessive} strongest subject and a source of pride.`,
    `Good work, {studentName}! With {averageScore}% average, {pronoun} has shown consistent effort throughout the term.`,
    `{studentName} has achieved a good {averageScore}% average. {possessive} {bestScore}% in {bestSubject} is truly commendable.`,
    `Solid performance, {studentName}! {pronoun} has earned {averageScore}% average. {bestSubject} ({bestScore}%) is a highlight worth celebrating.`,
    `{studentName} has shown good academic ability with {averageScore}% average. {possessive} performance in {bestSubject} is noteworthy and inspiring.`,
    `Good results, {studentName}! With {averageScore}% average, {pronoun} has met the required standards with room to grow further.`,
    `{studentName} has achieved a good {averageScore}% average. Keep up the wonderful work!`,
    `Commendable work, {studentName}! {pronoun} has earned {averageScore}% average, showing solid understanding across subjects.`,
    `{studentName} has performed well, achieving {averageScore}% average. {bestSubject} ({bestScore}%) is genuinely impressive.`,
    `Good effort, {studentName}! With {averageScore}% average, {pronoun} has shown consistent and steady progress.`,
    `{studentName} has achieved a good {averageScore}% average. {possessive} performance in {bestSubject} really stands out.`,
    `Solid results, {studentName}! {pronoun} has earned {averageScore}% average this term. Well done!`,
    `{studentName} has shown good understanding with {averageScore}% average. {bestSubject} ({bestScore}%) is a genuine strength.`,
    `Good performance, {studentName}! With {averageScore}% average, {pronoun} has met expectations beautifully.`,
    `{studentName} has achieved a good {averageScore}% average. Well done and keep going!`,
    `Commendable effort, {studentName}! {pronoun} has earned {averageScore}% average. Keep pushing forward!`,
    `{studentName} has performed well, achieving {averageScore}% average. {bestSubject} ({bestScore}%) is truly noteworthy.`,
    `Good work, {studentName}! With {averageScore}% average, {pronoun} has shown solid academic progress.`,
    `{studentName} has achieved a good {averageScore}% average. Keep up the excellent momentum!`,
    `Solid performance, {studentName}! {pronoun} has earned {averageScore}% average with real potential to grow.`,
    `{studentName} has shown good academic ability with {averageScore}% average. Well done!`,
    `Good results, {studentName}! With {averageScore}% average, {pronoun} has made commendable progress.`,
    `{studentName} has achieved a good {averageScore}% average. Continue striving for excellence!`,
  ],

  aboveAverage: [
    `{studentName} has made encouraging progress this term with {averageScore}% average. {pronoun} performed well in {bestSubject} ({bestScore}%) and shows real potential to strengthen {possessive} skills in {weakestSubject}. With continued practice and focus, {pronoun} can achieve greater success.`,
    `Encouraging performance, {studentName}. {pronoun} achieved {averageScore}% average, successfully passing all subjects. {possessive} best subject was {bestSubject} at {bestScore}%. Building on this strength while focusing on {weakestSubject} will bring even better results.`,
    `{studentName} has met the requirements with an above-average performance of {averageScore}%. {pronoun} performed best in {bestSubject} ({bestScore}%). Consistent effort in {weakestSubject} will unlock {possessive} full potential.`,
    `Good progress, {studentName}. With {averageScore}% average, {pronoun} has shown {pronoun.toLowerCase()} can succeed. Focused attention on {weakestSubject} will help {objective} reach higher levels of achievement.`,
    `{studentName} has achieved an above-average performance with {averageScore}%. {pronoun} excels in {bestSubject} ({bestScore}%) and has the ability to strengthen {weakestSubject} with dedicated practice.`,
    `Good results, {studentName}! With {averageScore}% average, {pronoun} has shown solid progress. {bestSubject} ({bestScore}%) is a wonderful strength to build upon.`,
    `{studentName} has performed encouragingly, earning {averageScore}% average. {possessive} {bestScore}% in {bestSubject} shows real potential for even greater achievement.`,
    `Well done, {studentName}! {pronoun} has achieved {averageScore}% average this term. {bestSubject} ({bestScore}%) is impressive and can inspire growth in other areas.`,
    `{studentName} has shown encouraging understanding with {averageScore}% average. Focusing on {weakestSubject} will help {objective} unlock even more potential.`,
    `Good performance, {studentName}! With {averageScore}% average, {pronoun} has made real progress. Continued effort will bring greater rewards.`,
    `{studentName} has achieved an above-average score of {averageScore}%. {possessive} {bestScore}% in {bestSubject} demonstrates real ability. Applying this to {weakestSubject} will bring success.`,
    `Encouraging results, {studentName}! {pronoun} has earned {averageScore}% average this term. {bestSubject} ({bestScore}%) stands out as a strong foundation for growth.`,
    `{studentName} has shown encouraging progress, achieving {averageScore}% average. With continued dedication to {weakestSubject}, {pronoun} will achieve more.`,
    `Good work, {studentName}! With {averageScore}% average, {pronoun} has demonstrated understanding. Consistent revision will strengthen {possessive} knowledge further.`,
    `{studentName} has achieved an above-average performance at {averageScore}%. {bestSubject} ({bestScore}%) is a wonderful strength worth developing further.`,
    `Commendable performance, {studentName}! {pronoun} has earned {averageScore}% average. {bestSubject} ({bestScore}%) shows what {pronoun} is capable of achieving.`,
    `{studentName} has shown encouraging academic ability with {averageScore}% average. Dedicating extra time to {weakestSubject} will build confidence and skills.`,
    `Good results, {studentName}! With {averageScore}% average, {pronoun} has succeeded. {bestSubject} ({bestScore}%) is impressive and can be further strengthened.`,
    `{studentName} has achieved {averageScore}% average. {possessive} performance in {bestSubject} is truly commendable and shows real potential.`,
    `Encouraging work, {studentName}! {pronoun} has earned {averageScore}% average this term. Continued effort will yield wonderful improvement.`,
    `{studentName} has performed encouragingly, achieving {averageScore}% average. A dedicated focus on {weakestSubject} will help balance {possessive} skills.`,
    `Good performance, {studentName}! With {averageScore}% average, {pronoun} has met expectations. There is exciting room to grow with continued effort.`,
    `{studentName} has shown encouraging understanding with {averageScore}% average. {bestSubject} ({bestScore}%) is a strength to leverage for further growth.`,
    `Well done, {studentName}! {pronoun} has earned {averageScore}% average. Hard work and dedication will bring wonderful success.`,
    `{studentName} has achieved an above-average score of {averageScore}%. Well done! Continued focus will bring even better results.`,
    `Good work, {studentName}! With {averageScore}% average, {pronoun} has shown real progress. Keep building on this solid foundation.`,
    `{studentName} has performed encouragingly, earning {averageScore}% average. {bestSubject} ({bestScore}%) is impressive and can inspire further growth.`,
    `Commendable performance, {studentName}! {pronoun} has achieved {averageScore}% average this term. Every step forward truly counts.`,
    `{studentName} has shown encouraging academic ability with {averageScore}% average. Continued effort will lead to wonderful improvement.`,
    `Good results, {studentName}! With {averageScore}% average, {pronoun} has succeeded. Great job! Aim to strengthen {weakestSubject}.`,
    `{studentName} has achieved {averageScore}% average. {possessive} performance in {bestSubject} is commendable and worth building upon.`,
  ],

  satisfactory: [
    `{studentName} has made steady progress this term, achieving {averageScore}% average. {pronoun} performed best in {bestSubject} ({bestScore}%). With continued dedication and focused attention on {weakestSubject}, {pronoun} will see significant improvement.`,
    `{studentName} has shown promising ability with {averageScore}% average this term. {bestSubject} ({bestScore}%) is {possessive} strongest area, and with the right support in {weakestSubject}, {pronoun} can achieve much more.`,
    `{studentName} has demonstrated understanding this term, averaging {averageScore}%. {pronoun} has the ability to strengthen {possessive} performance in {weakestSubject} with focused effort and consistent practice.`,
    `Encouraging results, {studentName}. {pronoun} achieved {averageScore}% average. {possessive} performance in {bestSubject} ({bestScore}%) is a real strength, and dedicated practice in {weakestSubject} will bring positive improvement.`,
    `{studentName} has performed at a satisfactory level with {averageScore}% average. {possessive} strength in {bestSubject} is evident at {bestScore}%. Building on this success will help in other areas.`,
    `Steady work, {studentName}! With {averageScore}% average, {pronoun} has succeeded. {bestSubject} ({bestScore}%) is a wonderful highlight to celebrate.`,
    `{studentName} has achieved encouraging results at {averageScore}% average. {possessive} {bestScore}% in {bestSubject} shows real potential for continued growth.`,
    `Commendable performance, {studentName}! {pronoun} has earned {averageScore}% average this term. {bestSubject} ({bestScore}%) is genuinely impressive.`,
    `{studentName} has shown steady understanding with {averageScore}% average. Focusing on {weakestSubject} will help {objective} continue to improve.`,
    `Encouraging results, {studentName}! With {averageScore}% average, {pronoun} has met expectations. Keep working hard!`,
    `{studentName} has achieved a satisfactory average of {averageScore}%. {possessive} {bestScore}% in {bestSubject} is truly promising.`,
    `Good work, {studentName}! {pronoun} has earned {averageScore}% average this term. With effort, {weakestSubject} will improve steadily.`,
    `{studentName} has performed steadily, achieving {averageScore}% average. {bestSubject} ({bestScore}%) stands out as a real strength.`,
    `Encouraging effort, {studentName}! With {averageScore}% average, {pronoun} has shown understanding. Continued focus will bring growth.`,
    `{studentName} has achieved {averageScore}% average. {possessive} performance in {bestSubject} is commendable and worth celebrating.`,
    `Steady performance, {studentName}! {pronoun} has earned {averageScore}% average this term. Keep pushing forward with confidence.`,
    `{studentName} has shown promising academic ability with {averageScore}% average. Dedicating time to {weakestSubject} will bring wonderful improvement.`,
    `Encouraging results, {studentName}! With {averageScore}% average, {pronoun} has succeeded. {bestSubject} ({bestScore}%) is great.`,
    `{studentName} has achieved {averageScore}% average. {possessive} performance in {bestSubject} is noteworthy and shows potential.`,
    `Good work, {studentName}! {pronoun} has earned {averageScore}% average this term. Hard work truly pays off.`,
    `{studentName} has performed steadily, achieving {averageScore}% average. A focus on {weakestSubject} will bring balance and success.`,
    `Encouraging performance, {studentName}! With {averageScore}% average, {pronoun} has met requirements. Keep building on this foundation.`,
    `{studentName} has shown steady understanding with {averageScore}% average. {bestSubject} ({bestScore}%) is a real strength.`,
    `Good results, {studentName}! {pronoun} has earned {averageScore}% average. Continued effort brings wonderful success.`,
    `{studentName} has achieved a satisfactory average of {averageScore}%. Well done and keep going!`,
    `Steady work, {studentName}! With {averageScore}% average, {pronoun} has shown progress. Keep it up!`,
    `{studentName} has performed steadily, earning {averageScore}% average. {bestSubject} ({bestScore}%) is genuinely good.`,
    `Commendable performance, {studentName}! {pronoun} has achieved {averageScore}% average this term. Every step forward counts.`,
    `{studentName} has shown promising academic ability with {averageScore}% average. Keep striving for continued improvement.`,
    `Encouraging results, {studentName}! With {averageScore}% average, {pronoun} has succeeded. Great job!`,
    `{studentName} has achieved {averageScore}% average. {possessive} performance in {bestSubject} is truly commendable.`,
  ],

  average: [
    `{studentName} has achieved an average of {averageScore}%. {pronoun} performed best in {bestSubject} ({bestScore}%). With consistent effort and focused practice in {weakestSubject}, {pronoun} will make significant progress. {possessive} potential is clear.`,
    `Credit-level achievement, {studentName}. With {averageScore}% average, {pronoun} has passed all subjects. {bestSubject} was {possessive} strongest at {bestScore}%. Continued focus on {weakestSubject} will bring exciting improvements.`,
    `{studentName} has met the required standard with an average of {averageScore}%. {pronoun} excels in {bestSubject} ({bestScore}%) and has the ability to strengthen {weakestSubject} with dedication and support.`,
    `Passing performance achieved. {studentName} scored {averageScore}% on average. {possessive} best subject is {bestSubject} ({bestScore}%). Developing effective strategies for {weakestSubject} will elevate overall performance.`,
    `{studentName} has achieved a credit-level performance with {averageScore}%. {possessive} strength in {bestSubject} is evident at {bestScore}%. Continued effort will bring wonderful improvement.`,
    `Solid results, {studentName}! With {averageScore}% average, {pronoun} has passed. {bestSubject} ({bestScore}%) is a wonderful highlight to celebrate.`,
    `{studentName} has earned {averageScore}% average this term. {possessive} {bestScore}% in {bestSubject} shows real potential for growth.`,
    `Credit performance, {studentName}! {pronoun} has achieved {averageScore}% average. {bestSubject} ({bestScore}%) is impressive.`,
    `{studentName} has shown understanding with {averageScore}% average. Focusing on {weakestSubject} will help build confidence and skills.`,
    `Passing performance, {studentName}! With {averageScore}% average, {pronoun} has met basic requirements. Keep working hard - improvement is within reach.`,
    `{studentName} has achieved an average of {averageScore}%. {possessive} {bestScore}% in {bestSubject} is genuinely good. Building on this will help other subjects.`,
    `Credit work, {studentName}! {pronoun} has earned {averageScore}% average this term. Extra effort on {weakestSubject} will bring wonderful progress.`,
    `{studentName} has performed at credit level, achieving {averageScore}% average. {bestSubject} ({bestScore}%) stands out as a real strength.`,
    `Solid effort, {studentName}! With {averageScore}% average, {pronoun} has shown understanding. Continued focus will bring growth.`,
    `{studentName} has achieved {averageScore}% average. {possessive} performance in {bestSubject} is commendable and worth building upon.`,
    `Credit performance, {studentName}! {pronoun} has earned {averageScore}% average this term. Keep pushing forward with confidence.`,
    `{studentName} has shown credit-level academic ability with {averageScore}% average. Dedicating time to {weakestSubject} will bring improvement.`,
    `Passing results, {studentName}! With {averageScore}% average, {pronoun} has succeeded. {bestSubject} ({bestScore}%) is genuinely good.`,
    `{studentName} has achieved {averageScore}% average. {possessive} performance in {bestSubject} is truly noteworthy.`,
    `Credit work, {studentName}! {pronoun} has earned {averageScore}% average this term. Hard work always pays off.`,
    `{studentName} has performed at credit level, achieving {averageScore}% average. A focus on {weakestSubject} will help {objective} grow.`,
    `Solid performance, {studentName}! With {averageScore}% average, {pronoun} has met requirements. Keep building on this solid foundation.`,
    `{studentName} has shown understanding with {averageScore}% average. {bestSubject} ({bestScore}%) is a real strength worth celebrating.`,
    `Credit results, {studentName}! {pronoun} has earned {averageScore}% average. Continued effort brings wonderful success.`,
    `{studentName} has achieved an average of {averageScore}%. Well done and keep going!`,
    `Solid work, {studentName}! With {averageScore}% average, {pronoun} has shown progress. Keep it up!`,
    `{studentName} has performed at credit level, earning {averageScore}% average. {bestSubject} ({bestScore}%) is genuinely good.`,
    `Credit performance, {studentName}! {pronoun} has achieved {averageScore}% average this term. Every step forward truly counts.`,
    `{studentName} has shown credit-level academic ability with {averageScore}% average. Keep striving for continued improvement.`,
    `Solid results, {studentName}! With {averageScore}% average, {pronoun} has succeeded. Well done!`,
    `{studentName} has achieved {averageScore}% average. {possessive} performance in {bestSubject} is truly commendable.`,
  ],

  belowAverage: [
    `{studentName} has shown clear potential this term with {averageScore}% average. {pronoun} performed encouragingly in {bestSubject} ({bestScore}%) and has real capacity to build {possessive} skills in {weakestSubject} with the right support. {pronoun} is capable of significant growth with consistent practice and encouragement.`,
    `{studentName} achieved {averageScore}% average this term, showing real ability. {possessive} {bestScore}% in {bestSubject} demonstrates {possessive} capability. With targeted guidance in {weakestSubject}, {pronoun} can make meaningful progress. We believe in {possessive} potential and are here to support {objective} every step of the way.`,
    `{studentName} has passed this term with {averageScore}% average. {bestSubject} ({bestScore}%) shows what {pronoun} can achieve when engaged. {pronoun} has real ability in {weakestSubject} that can be unlocked with focused attention and consistent effort.`,
    `{studentName}, you have shown that you can succeed with {averageScore}% average this term. {bestSubject} ({bestScore}%) is your strength, and we know you can build similar skills in {weakestSubject}. Please speak with your teachers - they are eager to help you grow.`,
    `{studentName} passed with {averageScore}% average, showing real determination. {possessive} {bestScore}% in {bestSubject} demonstrates {possessive} capability. With focused effort on {weakestSubject}, {pronoun} will raise {possessive} overall performance significantly.`,
    `{studentName} has shown ability worth developing. With {averageScore}% average, {pronoun} has demonstrated potential. We believe {possessive} best is yet to come with continued support and encouragement.`,
    `{studentName} achieved {averageScore}% average this term. {bestSubject} ({bestScore}%) is a wonderful strength to build upon. {pronoun} is encouraged to seek support in {weakestSubject} - help is always available.`,
    `{studentName} passed with {averageScore}% average, showing determination. {possessive} performance in {bestSubject} reveals real potential. With continued support in {weakestSubject}, greater achievements await.`,
    `{studentName} has shown the ability to succeed, achieving {averageScore}% average. With more consistent effort, especially in {weakestSubject}, {pronoun} will unlock {possessive} true potential.`,
    `{studentName} demonstrated real ability with {averageScore}% average this term. {pronoun} has passed and shown promise. We are committed to helping {objective} grow through targeted support and encouragement.`,
    `{studentName} achieved {averageScore}% average. {weakestSubject} at {weakestScore}% needs strengthening. With the right guidance and consistent effort, {pronoun} will show wonderful improvement.`,
    `{studentName} passed with {averageScore}% average, showing what {pronoun} can do. {bestSubject} ({bestScore}%) is a strength that can inspire success in other subjects.`,
    `{studentName} achieved {averageScore}% average. {possessive} performance in {bestSubject} is genuinely encouraging. We know {pronoun} can build similar success in weaker areas with support.`,
    `{studentName} has shown promise with {averageScore}% average. {pronoun} needs continued support and encouragement to grow. We are committed to helping {objective} succeed.`,
    `{studentName} met the pass mark at {averageScore}%. Focusing on {weakestSubject} will bring balance and confidence to {possessive} overall performance.`,
    `{studentName} passed with {averageScore}% average. {bestSubject} ({bestScore}%) is a genuine strength. With consistent effort and support, {pronoun} will achieve much more.`,
    `{studentName} achieved {averageScore}% average. {weakestSubject} deserves focused attention. Additional support and consistent practice will bring wonderful improvement.`,
    `{studentName} has shown potential worth nurturing. With {averageScore}% average, {pronoun} has succeeded and can do even more with continued dedication.`,
    `{studentName} achieved {averageScore}% average. {possessive} {bestScore}% in {bestSubject} shows real ability. We believe in {possessive} capacity to grow.`,
    `{studentName} passed with {averageScore}% average, showing determination. Continued effort on {weakestSubject} will bring exciting improvement.`,
    `{studentName} achieved {averageScore}% average. {bestSubject} ({bestScore}%) is a real highlight. {pronoun} can use this strength as a foundation for growth in other areas.`,
    `{studentName} has shown promise with {averageScore}% average. {pronoun} needs targeted support in {weakestSubject}. We are here to help - improvement is absolutely possible.`,
    `{studentName} met requirements at {averageScore}%. Building skills in {weakestSubject} will help {objective} grow with confidence.`,
    `{studentName} passed with {averageScore}% average, showing capability. {bestSubject} ({bestScore}%) is truly good. Keep pushing - success is within reach.`,
    `{studentName} achieved {averageScore}% average. With continued effort on {weakestSubject}, {pronoun} will make significant, measurable progress.`,
    `{studentName} has shown ability worth developing. With {averageScore}% average, {pronoun} has passed. We are here to support {possessive} journey to greater success.`,
    `{studentName} achieved {averageScore}% average. {weakestSubject} at {weakestScore}% deserves focused attention. With consistent practice, wonderful improvement is possible.`,
    `{studentName} passed with {averageScore}% average. {bestSubject} ({bestScore}%) shows real promise. Building on this success will bring greater achievements.`,
    `{studentName} achieved {averageScore}% average. {possessive} performance in {bestSubject} is encouraging. We believe {pronoun} can build similar success in all subjects.`,
    `{studentName} has shown potential this term with {averageScore}% average. {pronoun} deserves continued support and encouragement to reach {possessive} true potential.`,
    `{studentName} passed with {averageScore}% average, showing determination. A dedicated focus on {weakestSubject} will help {objective} improve significantly.`,
  ],

  marginal: [
    `{studentName} has shown determination this term, passing with {averageScore}% average. {possessive} performance in {bestSubject} ({bestScore}%) reveals real ability. We believe {pronoun} can build {possessive} skills in {weakestSubject} with focused support and consistent effort. Every student has unique strengths, and we are committed to helping {objective} discover and develop {possessive}.`,
    `{studentName} achieved {averageScore}% average, meeting the minimum requirements this term. {bestSubject} ({bestScore}%) was {possessive} strongest area, showing what {pronoun} is capable of. With dedicated support in {weakestSubject}, {pronoun} will make meaningful, measurable progress. We believe in {possessive} ability to grow.`,
    `{studentName} has passed this term with {averageScore}% average. {weakestSubject} at {weakestScore}% deserves focused attention. With additional academic support and consistent practice, {pronoun} will build the understanding and confidence needed to succeed. We are here to help every step of the way.`,
    `{studentName} passed with {averageScore}% average this term, showing perseverance. {possessive} performance indicates areas where growth is possible, especially in {weakestSubject}. We recommend extra practice and support to help {objective} unlock {possessive} full potential. Improvement is absolutely within reach.`,
    `{studentName} achieved {averageScore}% average this term. {possessive} {bestScore}% in {bestSubject} shows real potential. With focused effort and support in {weakestSubject}, {pronoun} will demonstrate wonderful growth. We believe in {possessive} ability to succeed.`,
    `{studentName} has shown determination this term. With {averageScore}% average, {pronoun} has passed. We are committed to supporting {possessive} continued growth with encouragement and targeted help.`,
    `{studentName} passed with {averageScore}% average, showing perseverance. {bestSubject} ({bestScore}%) was a real strength. With continued support in {weakestSubject}, {pronoun} will thrive.`,
    `{studentName} achieved {averageScore}% average this term. {weakestSubject} at {weakestScore}% deserves attention. With consistent support and dedication, {pronoun} will make wonderful progress.`,
    `{studentName} met requirements at {averageScore}%. {possessive} {bestScore}% in {bestSubject} was encouraging. Strengthening {weakestSubject} will bring balance and success.`,
    `{studentName} has shown determination with {averageScore}% average. With continued support and effort, {pronoun} will make wonderful progress. We believe in {possessive} potential.`,
    `{studentName} passed with {averageScore}% average, showing perseverance. {weakestSubject} deserves focused attention. Additional practice and support will bring meaningful improvement.`,
    `{studentName} achieved {averageScore}% average. {bestSubject} ({bestScore}%) is a genuine strength. Building confidence in this area can inspire growth in {weakestSubject}.`,
    `{studentName} passed at {averageScore}%, showing determination. {possessive} performance in {bestSubject} is encouraging. With continued effort, {pronoun} will improve significantly.`,
    `{studentName} has shown perseverance this term with {averageScore}% average. Continued support and encouragement will help {objective} succeed. We are committed to {possessive} growth.`,
    `{studentName} met expectations at {averageScore}%. Focusing on {weakestSubject} with additional support will bring wonderful improvement and confidence.`,
    `{studentName} passed with {averageScore}% average, showing determination. {bestSubject} ({bestScore}%) was genuinely good. Building on this will inspire success in other areas.`,
    `{studentName} achieved {averageScore}% average this term. {weakestSubject} at {weakestScore}% needs support. With consistent effort and guidance, meaningful improvement is absolutely possible.`,
    `{studentName} has shown determination with {averageScore}% average. {pronoun} deserves continued encouragement and support. We believe in {possessive} ability to grow and succeed.`,
    `{studentName} passed with {averageScore}% average, showing perseverance. {possessive} {bestScore}% in {bestSubject} shows real potential. Keep pushing - growth is possible!`,
    `{studentName} achieved {averageScore}% average this term. Continued effort on {weakestSubject} with support will bring exciting improvement. We are here to help.`,
    `{studentName} passed at {averageScore}%, showing perseverance. {bestSubject} ({bestScore}%) is a real highlight. Use this as inspiration to build skills in weaker areas.`,
    `{studentName} has shown determination this term with {averageScore}% average. Continued support will help {objective} improve. We are committed to {possessive} success.`,
    `{studentName} met requirements at {averageScore}%. Focused work on {weakestSubject} with proper support will help {objective} improve significantly.`,
    `{studentName} passed with {averageScore}% average, showing effort. {bestSubject} ({bestScore}%) was genuinely good. Keep working - improvement is absolutely within reach.`,
    `{studentName} achieved {averageScore}% average this term. {weakestSubject} deserves focused attention and support. Meaningful growth is possible with consistent effort.`,
    `{studentName} has shown perseverance with {averageScore}% average. {pronoun} will improve significantly with continued support and encouragement. We believe in {possessive} potential.`,
    `{studentName} passed with {averageScore}% average, showing determination. {possessive} performance in {bestSubject} is promising. Building on this foundation will bring greater success.`,
    `{studentName} achieved {averageScore}% average this term. Continued effort on {weakestSubject} with support will bring wonderful improvement. Every step matters.`,
    `{studentName} passed at {averageScore}%, showing determination. {bestSubject} ({bestScore}%) is a real strength to build upon. Keep pushing forward.`,
    `{studentName} has shown perseverance with {averageScore}% average. {pronoun} needs continued support. We are committed to helping {objective} grow and succeed.`,
    `{studentName} passed with {averageScore}% average, showing effort. Focusing on improvement areas with dedicated support will help {objective} thrive.`,
  ],

  poor: [
    `{studentName} has faced significant challenges this term but showed genuine effort in reaching {averageScore}% average. Every student learns at {possessive} own pace, and with additional academic support, a personalized learning plan, and consistent encouragement, {pronoun} can achieve wonderful progress. We firmly believe in {possessive} potential and are committed to partnering with parents to unlock it.`,
    `{studentName} achieved {averageScore}% average this term - a starting point from which real growth is possible. {weakestSubject} needs particular attention, but with extra lessons, patient support, and consistent practice, {pronoun} will build the confidence and understanding needed to succeed. A collaborative approach between school and home will make a meaningful difference.`,
    `{studentName}'s performance this term ({averageScore}% average) indicates areas where targeted support will make a significant difference. {weakestSubject} deserves focused attention through additional academic help and a personalized learning approach. Every student has strengths to build upon, and we are dedicated to helping {objective} discover and develop {possessive}.`,
    `{studentName} has shown that {pronoun} needs additional support this term, achieving {averageScore}% average. With extra tutoring, patient encouragement, and consistent practice, {pronoun} will make meaningful progress. We warmly invite parents to partner with us in creating a support plan that will help {objective} succeed and thrive.`,
    `{studentName} achieved {averageScore}% average this term. {weakestSubject} at {weakestScore}% needs focused support. With targeted intervention, consistent effort, and encouragement, {pronoun} will demonstrate real growth. Additional academic support is warmly recommended - we are here to help.`,
    `{studentName} has shown perseverance despite challenges this term. With {averageScore}% average, {pronoun} deserves continued support and encouragement. We are committed to helping {objective} unlock {possessive} potential.`,
    `{studentName} achieved {averageScore}% average. {weakestSubject} ({weakestScore}%) needs targeted support. With patient guidance and consistent practice, meaningful improvement is absolutely possible. Extra lessons are warmly recommended.`,
    `{studentName} has shown determination that deserves recognition, achieving {averageScore}% average. With additional support and a structured study plan, {pronoun} will make wonderful progress. We are committed to helping {objective} thrive.`,
    `{studentName} scored {averageScore}% average this term. {weakestSubject} needs immediate, patient support. We warmly encourage parents to work with the school in creating a personalized support plan that will help {objective} succeed.`,
    `{studentName} has shown effort this term, achieving {averageScore}% average. With targeted support, encouragement, and consistent practice, {pronoun} will demonstrate meaningful improvement. We believe in {possessive} ability with the right help.`,
    `{studentName} performed below the expected level at {averageScore}%. A parent-teacher meeting is warmly encouraged to discuss {possessive} needs and create a supportive plan for growth. We are eager to partner with you.`,
    `{studentName} achieved {averageScore}% average this term. {weakestSubject} deserves attention with additional support and regular practice. Every student can grow with the right encouragement - we are committed to helping {objective}.`,
    `{studentName} has shown areas where support is needed at {averageScore}%. Academic intervention will help {objective} build the confidence and skills needed. We are here to partner with you in {possessive} learning journey.`,
    `{studentName} has faced challenges this term with {averageScore}% average. {pronoun} deserves patient support and encouragement. Extra lessons and consistent practice will help {objective} make wonderful progress.`,
    `{studentName} scored {averageScore}% average this term. {weakestSubject} needs focused, patient support. We warmly recommend additional tutoring to help {objective} build confidence and understanding.`,
    `{studentName} achieved {averageScore}% average. Extra lessons and consistent support are warmly recommended. We invite parents to partner with the school in helping {objective} thrive academically.`,
    `{studentName} has shown effort at {averageScore}%, though {weakestSubject} at {weakestScore}% needs attention. With patient support and encouragement, meaningful improvement is absolutely possible.`,
    `{studentName} has faced challenges this term with {averageScore}% average. {pronoun} deserves continued support. We are firmly committed to helping {objective} unlock {possessive} potential through targeted assistance.`,
    `{studentName} underperformed at {averageScore}%, but every student has the capacity to grow. {weakestSubject} needs targeted support. Additional academic help is warmly recommended.`,
    `{studentName} achieved {averageScore}% average. Extra lessons are warmly encouraged to help {objective} build the foundation needed for success. Every step matters and every effort counts.`,
    `{studentName} scored below expectations at {averageScore}%. Immediate support and encouragement will help {objective} improve. We invite parents to partner with us in creating a plan for growth.`,
    `{studentName} has faced challenges but shown perseverance, achieving {averageScore}% average. With continued support and consistent effort, {pronoun} will demonstrate wonderful progress.`,
    `{studentName} performed below expectations at {averageScore}%. {weakestSubject} needs patient support. We warmly encourage parents to partner with the school in {possessive} academic journey.`,
    `{studentName} has shown areas where support is needed. {pronoun} achieved {averageScore}% average this term. Academic support is warmly recommended to help {objective} thrive.`,
    `{studentName} underperformed at {averageScore}%. A warm parent-teacher meeting is encouraged to discuss {possessive} needs and create a supportive path forward.`,
    `{studentName} achieved {averageScore}% average. With additional support and consistent effort, {pronoun} will make wonderful progress. Every student deserves the chance to grow and shine.`,
    `{studentName} has faced challenges this term with {averageScore}% average. {weakestSubject} needs particular attention. Extra tutoring will make a meaningful difference in {possessive} growth.`,
    `{studentName} scored below expectations at {averageScore}%. With extra support and patient guidance, {pronoun} will build the confidence and skills needed to succeed.`,
    `{studentName} has shown effort but needs additional support at {averageScore}%. We are here to help {objective} every step of the way. Improvement is absolutely within reach.`,
    `{studentName} has faced challenges this term with {averageScore}% average. With focused intervention and continued encouragement, {pronoun} will demonstrate real growth. We believe in {possessive} potential.`,
    `{studentName} underperformed at {averageScore}%. {weakestSubject} needs patient, focused work. Additional academic support and encouragement will bring meaningful improvement.`,
  ],

  veryPoor: [
    `{studentName} has faced significant challenges this term, achieving {averageScore}% average. Every student has unique potential and learns differently, and with intensive academic support, patient encouragement, and a personalized learning plan, {pronoun} can make wonderful progress. We warmly invite parents to partner with the school in creating a supportive environment where {pronoun} can discover {possessive} strengths and thrive. We are committed to helping {objective} succeed - improvement is absolutely possible with the right support.`,
    `{studentName} scored {averageScore}% average this term, indicating that additional support is needed to help {objective} succeed. {weakestSubject} particularly deserves focused, patient attention. We warmly recommend comprehensive academic support, extra lessons, and a parent-teacher conference to discuss strategies that will help {objective} grow with confidence. Every student can flourish with the right encouragement and guidance.`,
    `{studentName}'s performance this term requires our collective attention and care. With {averageScore}% average, {weakestSubject} at {weakestScore}% needs particular focus. We strongly recommend an integrated approach - intensive tutoring, patient guidance, and strong home-school collaboration. Every child has strengths waiting to be discovered, and we are committed to helping {objective} find and develop {possessive}.`,
    `{studentName} has underperformed significantly this term, achieving {averageScore}% average. However, every student has the capacity to grow with the right support. {weakestSubject} needs immediate, patient intervention through extra lessons and personalized learning approaches. A warm parent-teacher meeting is encouraged to discuss how we can work together to help {objective} succeed.`,
    `{studentName} performed below expectations with {averageScore}% average. {weakestSubject} at {weakestScore}% needs urgent, patient attention. Intensive academic support and consistent practice will help {objective} build the foundation needed. We invite parents to partner with us - together, we can help {objective} thrive.`,
    `{studentName} has faced significant challenges this term. With {averageScore}% average, {pronoun} needs comprehensive support. We are firmly committed to helping {objective} discover {possessive} strengths and succeed with patient guidance.`,
    `{studentName} underperformed at {averageScore}%. {weakestSubject} needs immediate, patient support. Extra lessons and regular practice will make a meaningful difference in {possessive} growth.`,
    `{studentName} has shown that {pronoun} needs significant support this term at {averageScore}%. With patient encouragement and consistent help, meaningful progress is absolutely possible. We strongly recommend extra lessons.`,
    `{studentName} scored significantly below expectations at {averageScore}%. {weakestSubject} needs comprehensive intervention. With patient support and encouragement, {pronoun} will grow. We are here to help.`,
    `{studentName} has faced serious challenges with {averageScore}% average. Every child deserves support to grow. Intensive help is warmly recommended - we are committed to {possessive} success.`,
    `{studentName} performed significantly below expectations at {averageScore}%. A warm parent-teacher meeting is strongly encouraged to discuss {possessive} needs and create a comprehensive support plan.`,
    `{studentName} achieved {averageScore}% average. {weakestSubject} needs focused, patient intervention. We warmly recommend comprehensive academic support to help {objective} build understanding.`,
    `{studentName} underperformed at {averageScore}%. Immediate academic intervention with patient support is needed. We are firmly committed to helping {objective} grow and succeed.`,
    `{studentName} has faced significant challenges with {averageScore}% average. Comprehensive support is needed. Extra tutoring and patient encouragement will help {objective} thrive.`,
    `{studentName} scored significantly below standard at {averageScore}%. {weakestSubject} needs patient, dedicated work. We warmly encourage parents to partner with us in supporting {possessive} growth.`,
    `{studentName} has shown that intensive support is needed at {averageScore}%. Remedial classes and patient encouragement are warmly recommended. Every student can grow with the right help.`,
    `{studentName} performed significantly below expectations at {averageScore}%. {weakestSubject} at {weakestScore}% needs focused support. Intensive help is warmly recommended.`,
    `{studentName} has faced significant challenges this term. {averageScore}% average shows areas needing patient support. We warmly recommend comprehensive intervention and encouragement.`,
    `{studentName} underperformed at {averageScore}%. {weakestSubject} needs immediate, patient attention. We are firmly committed to helping {objective} discover {possessive} potential.`,
    `{studentName} has faced serious challenges with {averageScore}% average. Extra lessons and warm encouragement are strongly recommended. We believe in {possessive} capacity to grow.`,
    `{studentName} scored significantly below expectations at {averageScore}%. Immediate patient action is encouraged to support {possessive} learning journey. Every child can succeed.`,
    `{studentName} has faced significant challenges, achieving {averageScore}% average. With intensive support and patient encouragement, meaningful improvement is absolutely possible.`,
    `{studentName} performed significantly below standard at {averageScore}%. {weakestSubject} needs urgent, patient support. We warmly invite parents to partner with the school.`,
    `{studentName} has shown areas needing significant support. With {averageScore}% average, {pronoun} deserves patient, dedicated help. We are committed to {possessive} success.`,
    `{studentName} underperformed at {averageScore}%. A warm parent-teacher conference is strongly encouraged to create a supportive plan for {possessive} growth.`,
    `{studentName} has faced significant challenges with {averageScore}% average. Comprehensive intervention and patient support are needed. We are here to help every step of the way.`,
    `{studentName} performed significantly below expectations at {averageScore}%. {weakestSubject} is an area needing focused support. Extra tutoring is warmly recommended.`,
    `{studentName} has shown that comprehensive help is needed at {averageScore}%. We warmly recommend extra support and patient encouragement. Every student can grow.`,
    `{studentName} scored significantly below expectations at {averageScore}%. Immediate patient intervention is needed. We are firmly here to help {objective} succeed.`,
    `{studentName} has faced significant challenges with {averageScore}% average. Major intervention with patient support is needed. We firmly believe improvement is possible.`,
    `{studentName} underperformed at {averageScore}%. {weakestSubject} needs urgent, patient work. Additional academic support and encouragement are warmly recommended.`,
  ],
}

// ═══════════════════════════════════════════════════════════════
// PRINCIPAL COMMENTS — Encouraging & Supportive (No Promotion Talk)
// ═══════════════════════════════════════════════════════════════
const PRINCIPAL_COMMENTS: Record<string, string[]> = {
  outstanding: [
    `The Management commends {studentName} for an outstanding academic performance with {averageScore}% average. {pronoun} has demonstrated excellence, discipline, and intellectual prowess. We are very proud of this achievement. Keep up the wonderful work!`,
    `Exceptional results! {studentName} achieved {averageScore}% average, placing {objective} among the best students. The school is very proud of this achievement.`,
    `Remarkable performance. {studentName} scored {averageScore}% on average, showing mastery across all subjects. Continue this excellent trajectory.`,
    `Outstanding achievement, {studentName}! {pronoun} has set a benchmark with {averageScore}% average. Wonderful work — keep it up!`,
    `Superb results! {studentName} earned {averageScore}% average. Keep shining!`,
    `Exceptional academic display. {studentName} has earned high honors for {averageScore}% average.`,
    `Brilliant performance! {studentName} achieved {averageScore}% average. Well done!`,
    `Outstanding work, {studentName}! Exceptional results throughout.`,
    `Remarkable achievement! {studentName} scored {averageScore}% average. Truly impressive!`,
    `Top-tier performance, {studentName}! Very proud!`,
    `Exceptional results! Keep excelling!`,
    `Outstanding academic effort by {studentName}! Congratulations!`,
    `Superb achievement! Well done!`,
    `Brilliant work, {studentName}! Continue this momentum.`,
    `Exceptional performance! Well deserved!`,
    `Outstanding results! Very impressive!`,
    `Remarkable academic journey! Keep it up!`,
    `Superb effort, {studentName}!`,
    `Exceptional achievement! Keep soaring!`,
    `Outstanding work! You have made us proud.`,
    `Brilliant performance! Well done!`,
    `Exceptional results! Very proud!`,
    `Outstanding academic display! Continue this excellent work.`,
    `Superb achievement, {studentName}! Congratulations!`,
    `Brilliant work! Keep it up!`,
    `Exceptional performance, {studentName}! Well deserved!`,
    `Outstanding results! Very impressive!`,
    `Remarkable work! Continue excelling!`,
    `Superb academic term! Keep this momentum.`,
    `Exceptional achievement, {studentName}! Well done!`,
    `Outstanding performance! Very proud of you!`,
  ],

  excellent: [
    `The Management congratulates {studentName} on an excellent performance ({averageScore}% average). {pronoun} has shown remarkable dedication to {possessive} studies. Well done!`,
    `Excellent results, {studentName}! With {averageScore}% average, {pronoun} has demonstrated strong academic ability. Keep striving for excellence.`,
    `Very impressive performance. {studentName} achieved {averageScore}% average, showing consistent effort and understanding. Continue this momentum.`,
    `Excellent work, {studentName}! Great job on {averageScore}% average.`,
    `Very good results! Keep it up!`,
    `Impressive performance, {studentName}! Well done!`,
    `Excellent academic display! Very proud!`,
    `Very impressive, {studentName}! Great consistent effort.`,
    `Good results! Continue striving!`,
    `Excellent achievement, {studentName}! Well deserved!`,
    `Very good work! Keep pushing!`,
    `Impressive results, {studentName}! Well done!`,
    `Excellent performance! Very proud!`,
    `Very impressive, {studentName}! Great effort throughout.`,
    `Good achievement! Continue this trajectory.`,
    `Excellent work! Well deserved recognition!`,
    `Very good results, {studentName}! Keep it up!`,
    `Impressive performance! Very well done.`,
    `Excellent academic term!`,
    `Very impressive, {studentName}! Great consistency.`,
    `Good work! Well done!`,
    `Excellent results! Very proud!`,
    `Very impressive achievement!`,
    `Impressive work, {studentName}! Keep striving!`,
    `Excellent performance, {studentName}! Well deserved!`,
    `Very good results! Continue excelling!`,
    `Impressive academic display!`,
    `Excellent work, {studentName}! Great consistent effort.`,
    `Very impressive! Continue this excellent work!`,
    `Good achievement! Keep it up!`,
    `Excellent results, {studentName}! Very proud of you!`,
  ],

  veryGood: [
    `The Management acknowledges {studentName}'s very good performance ({averageScore}% average). {pronoun} has shown great promise and consistency. Keep building on this foundation.`,
    `Good results, {studentName}. With {averageScore}% average, {pronoun} is on the right track. With continued effort, excellence is within reach.`,
    `Satisfactory performance. {studentName} scored {averageScore}% on average, meeting the expected standards. Aim higher for even better outcomes.`,
    `Very good work, {studentName}! Keep up the good effort.`,
    `Good performance! Continue building on this foundation.`,
    `Satisfactory results, {studentName}! Aim higher next time.`,
    `Very good effort! Keep striving for excellence.`,
    `Good work, {studentName}! With more effort, excellence awaits.`,
    `Satisfactory progress! Well done!`,
    `Very good achievement! Keep pushing forward.`,
    `Good results! Continue this momentum.`,
    `Satisfactory work, {studentName}! Aim for higher grades.`,
    `Very good performance! Keep up the consistency.`,
    `Good effort! Well deserved!`,
    `Satisfactory results, {studentName}! Continue striving.`,
    `Very good work! Keep building on this foundation.`,
    `Good achievement! Well done!`,
    `Satisfactory progress! Aim higher!`,
    `Very good results! Keep it up!`,
    `Good performance! Continue this trajectory.`,
    `Satisfactory work, {studentName}! Well deserved!`,
    `Very good effort! Keep pushing!`,
    `Good results! Well done!`,
    `Satisfactory achievement! Keep striving!`,
    `Very good work, {studentName}! Continue the good work.`,
    `Good progress! Aim for excellence.`,
    `Satisfactory performance! Well done!`,
    `Very good results! Keep it up!`,
    `Good effort! Continue this momentum.`,
    `Satisfactory work! Well deserved!`,
    `Very good achievement! Keep building!`,
  ],

  good: [
    `{studentName} has performed well with {averageScore}% average. {pronoun} has shown understanding across most subjects. Keep working hard.`,
    `Good effort, {studentName}. With {averageScore}% average, {pronoun} has met the basic requirements. There is room for improvement, so stay focused.`,
    `Commendable progress. {studentName} achieved {averageScore}% average, showing improvement in key areas. Continue building on this momentum.`,
    `Good work, {studentName}! Keep working hard.`,
    `Satisfactory performance! Room for improvement.`,
    `Commendable effort, {studentName}! Continue building.`,
    `Good results! Stay focused.`,
    `Satisfactory work, {studentName}! Keep pushing forward.`,
    `Good progress! Well done!`,
    `Commendable achievement! Keep it up!`,
    `Good effort! Aim higher next time.`,
    `Satisfactory results! Well deserved.`,
    `Good work, {studentName}! Continue this momentum.`,
    `Commendable performance! Keep striving.`,
    `Good results! Well done!`,
    `Satisfactory effort! Room for growth.`,
    `Good progress! Keep it up!`,
    `Commendable work! Well deserved.`,
    `Good achievement! Continue building.`,
    `Satisfactory results! Stay focused.`,
    `Good effort, {studentName}! Keep working hard.`,
    `Commendable progress! Well done!`,
    `Good work! Aim higher.`,
    `Satisfactory performance! Keep it up!`,
    `Good results! Continue striving.`,
    `Commendable effort! Well deserved.`,
    `Good progress! Keep building.`,
    `Satisfactory work! Stay focused.`,
    `Good achievement! Well done!`,
    `Commendable results! Keep pushing!`,
    `Good effort, {studentName}! Continue this momentum.`,
  ],

  aboveAverage: [
    `{studentName} achieved an above-average performance of {averageScore}%. {pronoun} has passed and shown potential for growth. Continued dedication will bring wonderful improvement.`,
    `Encouraging performance. {studentName} scored {averageScore}% on average, meeting the standard. Aiming higher with focused effort will bring exciting outcomes.`,
    `Good progress. {studentName} achieved {averageScore}% average. {pronoun} is encouraged to strengthen {weakestSubject} to achieve even better results. Growth is within reach.`,
    `Encouraging performance, {studentName}! Building skills in weaker areas will bring wonderful improvement.`,
    `Above-average results! Aim higher - potential is clear.`,
    `Good work, {studentName}! Room for exciting improvement with continued effort.`,
    `Encouraging achievement! Working on weaker areas will bring growth.`,
    `Above-average effort! Keep striving for continued success.`,
    `Good results! Focus on challenging subjects will pay off.`,
    `Encouraging work, {studentName}! Dedication to weaker areas will bring wonderful progress.`,
    `Above-average performance! Aim for excellence with continued effort.`,
    `Good progress! More effort will bring exciting results.`,
    `Encouraging results! Keep pushing forward with confidence.`,
    `Above-average work! Strive for growth - success awaits.`,
    `Good achievement! Room to grow with continued dedication.`,
    `Encouraging effort, {studentName}! Consistent effort will bring wonderful success.`,
    `Above-average results! Aim higher and reach for the stars.`,
    `Good work! Focus on learning will bring growth.`,
    `Encouraging performance! Dedication will bring wonderful improvement.`,
    `Above-average progress! Keep striving for excellence.`,
    `Good results! More effort in weaker areas will pay off.`,
    `Encouraging work! Hard work will bring wonderful rewards.`,
    `Above-average achievement! Aim for better results with dedication.`,
    `Good effort! Room for exciting growth ahead.`,
    `Encouraging results! Stay focused on continued improvement.`,
    `Above-average work! Keep pushing forward.`,
    `Good performance! More dedication will bring greater success.`,
    `Encouraging progress! Consistent effort will help {objective} grow.`,
    `Above-average results! Aim higher - potential is clear.`,
    `Good work! Focus and dedication will bring success.`,
    `Encouraging achievement! Keep striving for continued growth.`,
  ],

  satisfactory: [
    `{studentName} achieved a satisfactory average of {averageScore}%. {pronoun} has met the requirements and shown potential. Continued effort and dedication will bring wonderful improvements.`,
    `Encouraging performance, {studentName}. Continued hard work and focused practice will bring exciting improvement.`,
    `Steady results. {studentName} scored {averageScore}% average. Aiming for continued improvement will help {objective} succeed and thrive.`,
    `Steady work, {studentName}! More dedication to learning will bring wonderful growth.`,
    `Encouraging performance! Keep striving for continued success.`,
    `Steady progress! Room for exciting growth ahead.`,
    `Encouraging results! Aim higher with confidence.`,
    `Steady effort! Working on weaker areas will bring growth.`,
    `Encouraging work, {studentName}! Focus on challenging subjects will pay off.`,
    `Steady achievement! Keep pushing forward with determination.`,
    `Encouraging performance! More effort will bring wonderful results.`,
    `Steady results! Strive for continued growth.`,
    `Encouraging work! Dedication to learning will bring success.`,
    `Steady progress! Aim higher with confidence.`,
    `Encouraging results! Keep working hard - success awaits.`,
    `Steady effort! More focus on learning will bring growth.`,
    `Encouraging performance! Room to improve with continued dedication.`,
    `Steady work! Strive for excellence with continued effort.`,
    `Encouraging results! Keep pushing forward.`,
    `Steady progress! Work on weaknesses with focused practice.`,
    `Encouraging effort! Aim for continued growth.`,
    `Steady performance! More dedication will bring wonderful results.`,
    `Encouraging work! Stay focused on continued learning.`,
    `Steady results! Keep striving for even better outcomes.`,
    `Encouraging achievement! Room for exciting improvement.`,
    `Steady effort! Work harder next time with confidence.`,
    `Encouraging performance! Aim higher and reach for success.`,
    `Steady work! More effort needed for exciting growth.`,
    `Encouraging results! Keep building on this foundation.`,
    `Steady progress! Strive for even better next time.`,
    `Encouraging effort! Stay focused on continued success.`,
  ],

  average: [
    `{studentName} achieved a credit pass with {averageScore}% average. {pronoun} is encouraged to develop stronger study habits. Parental support and additional practice in weaker areas will help {objective} unlock {possessive} full potential.`,
    `Credit-level performance. {studentName} scored {averageScore}% on average. Continued hard work and consistent effort will bring wonderful improvement.`,
    `{studentName} passed with {averageScore}% average, demonstrating capability. {pronoun} is encouraged to build on {possessive} strengths while seeking support in weaker areas.`,
    `Credit pass, {studentName}! More effort and focus will bring even better results.`,
    `Solid performance! Hard work will bring wonderful improvement.`,
    `Credit results! Focus on effective learning strategies.`,
    `{studentName} passed! Dedication to studies will help {objective} thrive.`,
    `Credit work, {studentName}! Aim higher with consistent effort.`,
    `Solid achievement! Keep striving for better results.`,
    `Credit effort! Focus on challenging subjects will pay off.`,
    `{studentName} passed with credit. Working harder will bring exciting success.`,
    `Credit results! Consistent study habits will help {objective} grow.`,
    `Solid performance! Stay focused on learning goals.`,
    `Credit pass! More dedication to studies is warmly encouraged.`,
    `{studentName} passed! Aim for improvement in weaker areas.`,
    `Credit work! Keep pushing forward with determination.`,
    `Solid effort! Working harder will pay off.`,
    `Credit results! Focus on building stronger foundations.`,
    `{studentName} achieved credit. More consistent study will bring rewards.`,
    `Credit performance! Strive for better understanding.`,
    `Solid work! Dedication to learning will bring progress.`,
    `Credit pass! Aim higher with focused effort.`,
    `{studentName} passed! Keep working hard on all subjects.`,
    `Credit results! More effort in weaker areas is warmly encouraged.`,
    `Solid achievement! Stay focused on continuous improvement.`,
    `Credit work! Work harder on challenging concepts.`,
    `{studentName} passed with credit. Focus on developing stronger study skills.`,
    `Credit effort! Aim for growth in all subjects.`,
    `Solid performance! Keep striving for academic growth.`,
    `Credit results! More dedication to learning will bring success.`,
    `{studentName} passed! Studying with greater focus will help {objective} thrive.`,
  ],

  belowAverage: [
    `{studentName} passed with {averageScore}% average, showing determination. {pronoun} is encouraged to focus on continued improvement. We invite parents to partner with the school in supporting {possessive} learning journey - together, we can help {objective} thrive.`,
    `{studentName} achieved {averageScore}% average, demonstrating perseverance. {pronoun} is warmly encouraged to work with focused determination. Additional support in weaker subjects will help build the confidence and skills needed for greater success.`,
    `{studentName} passed successfully. We warmly encourage {objective} to focus on improvement areas with our full support. Parents are invited to partner with the school in creating a nurturing plan for growth.`,
    `{studentName} passed with {averageScore}% average, showing perseverance. Continued effort and warm encouragement will bring wonderful results. We believe in {possessive} potential!`,
    `{studentName} passed! Working with determination will bring exciting success. We are here to support {possessive} journey.`,
    `{studentName} succeeded with {averageScore}% average. Focused work on weaker areas with support will bring wonderful growth.`,
    `{studentName} passed and shows real potential. Parents are warmly invited to partner with us in supporting {possessive} learning.`,
    `{studentName} achieved a pass at {averageScore}%. With patient support and dedication, wonderful improvement is possible. We are here to help!`,
    `{studentName} passed! Consistent effort on weaker areas will bring exciting improvement.`,
    `{studentName} succeeded with {averageScore}% average. Focus on building stronger foundations with warm support.`,
    `{studentName} passed with determination. More dedicated effort will bring wonderful results. We believe in {possessive} capacity to grow.`,
    `{studentName} achieved success at {averageScore}%. Immediate action with patient support is warmly encouraged.`,
    `{studentName} passed successfully! Working harder with support will bring exciting growth.`,
    `{studentName} succeeded with {averageScore}% average. Focus on developing stronger study habits will help {objective} thrive.`,
    `{studentName} passed with encouraging effort. Parents are warmly advised to support learning at home.`,
    `{studentName} achieved success at {averageScore}%. Focused improvement in weaker areas is warmly encouraged.`,
    `{studentName} passed! More dedication to learning with support will bring wonderful growth.`,
    `{studentName} succeeded with determination. Studying harder with warm encouragement will bring success.`,
    `{studentName} passed with effort! Focus more on understanding key concepts with patient support.`,
    `{studentName} achieved a pass. Work on weak areas with teacher support will bring wonderful progress.`,
    `{studentName} succeeded with {averageScore}% average. Focused improvement with support will bring exciting results.`,
    `{studentName} passed! Parents are warmly encouraged to support learning at home.`,
    `{studentName} succeeded with determination. Continued effort and focus with support are warmly encouraged.`,
    `{studentName} passed! Working harder with warm support will bring success.`,
    `{studentName} achieved success. Focus on building skills in weak areas with encouragement.`,
    `{studentName} passed with encouraging effort. More consistent study habits are warmly recommended.`,
    `{studentName} succeeded with {averageScore}% average. Dedication and hard work with support will bring wonderful improvement.`,
    `{studentName} passed! Consistent action and warm support are warmly encouraged.`,
    `{studentName} succeeded with determination. Working harder on challenges with support will help {objective} thrive.`,
    `{studentName} achieved success. Focus on continuous improvement with warm encouragement.`,
    `{studentName} passed with effort. Parents are warmly encouraged to provide continued support.`,
  ],

  marginal: [
    `{studentName} passed successfully with {averageScore}% average, showing perseverance. We warmly encourage {objective} to focus on continued improvement. We invite parents to partner closely with the school to support {possessive} progress - every student can thrive with the right encouragement and guidance.`,
    `{studentName} succeeded this term. With additional support, patient encouragement, and consistent effort, {pronoun} will make wonderful progress. We firmly believe in {possessive} ability to grow and shine.`,
    `{studentName} passed with determination. {pronoun} deserves warm support and encouragement to build stronger skills. Parental partnership with the school is warmly welcomed - together, we can help {objective} thrive.`,
    `{studentName} passed with {averageScore}% average, showing perseverance! Continued effort with support will bring wonderful growth. We believe in you!`,
    `{studentName} succeeded despite challenges! Meaningful improvement is possible with continued support and encouragement.`,
    `{studentName} passed with determination! Focused effort with support will bring exciting growth.`,
    `{studentName} succeeded with perseverance! Working with determination will bring wonderful success.`,
    `{studentName} passed successfully! Improvement is warmly supported - we are here to help {objective} thrive.`,
    `{studentName} succeeded with effort! Parental support is warmly welcomed to help {objective} continue growing.`,
    `{studentName} passed with perseverance! Focus on building stronger foundations with patient support.`,
    `{studentName} succeeded with determination! Focused work with encouragement will bring wonderful progress.`,
    `{studentName} passed successfully! Continued dedication to studies with support is warmly encouraged.`,
    `{studentName} succeeded despite challenges! Improvement with continued support and encouragement will bring success.`,
    `{studentName} passed with effort! Focused approach to key subjects with warm support is warmly encouraged.`,
    `{studentName} succeeded with perseverance! Parents are warmly encouraged to support learning at home.`,
    `{studentName} passed! Working with determination will bring wonderful success.`,
    `{studentName} succeeded with encouraging effort! Continued effort with warm support will bring growth.`,
    `{studentName} passed with perseverance! Focused effort with warm encouragement will help {objective} thrive.`,
    `{studentName} succeeded! Focused approach with support will bring wonderful improvement.`,
    `{studentName} passed with determination! Continued dedication with support is warmly encouraged.`,
    `{studentName} succeeded with effort! Parental encouragement is warmly welcomed.`,
    `{studentName} passed with perseverance! Working with warm support will bring wonderful results.`,
    `{studentName} succeeded! Continued improvement is possible with patient support and encouragement.`,
    `{studentName} passed with effort! Focused work with support will bring exciting growth.`,
    `{studentName} succeeded with determination! Focused work with teacher guidance will bring wonderful progress.`,
    `{studentName} passed with perseverance! Continued focus on learning with support is warmly encouraged.`,
    `{studentName} succeeded! Parents are warmly encouraged to monitor progress and provide support.`,
    `{studentName} passed with effort! Working with determination will help {objective} thrive.`,
    `{studentName} succeeded despite challenges! Continued dedication to studies with support is warmly welcomed.`,
    `{studentName} passed with perseverance! Focused effort with encouragement will bring wonderful growth.`,
    `{studentName} succeeded! Focused improvement with warm support and encouragement will bring success.`,
  ],

  poor: [
    `{studentName} has faced challenges this term but shown genuine perseverance in achieving {averageScore}% average. We are warmly committed to providing additional support. We invite parents to partner closely with the school in creating a personalized learning plan that will help {objective} discover {possessive} strengths and thrive. Every student has unique potential - we are here to help {objective} unlock it.`,
    `{studentName} scored {averageScore}% average this term, demonstrating perseverance despite challenges. We are warmly dedicated to supporting {possessive} growth. Extra lessons, patient encouragement, and consistent practice will help {objective} build the foundation needed for wonderful success. A parent-teacher conference is warmly encouraged.`,
    `{studentName} has shown that {pronoun} needs additional support this term. We are warmly committed to comprehensive help. A personalized learning plan and regular parent-teacher collaboration will create the supportive environment where {pronoun} can grow with confidence and joy.`,
    `{studentName} has faced challenges this term! We are warmly committed to intensive support. Parent partnership and extra tutoring are warmly encouraged - we are here to help {objective} thrive.`,
    `{studentName} achieved with effort. We are warmly committed to immediate support. We firmly believe in {possessive} potential to grow and succeed!`,
    `{studentName} has shown perseverance! Extra lessons and warm support are warmly recommended to help {objective} thrive.`,
    `{studentName} achieved with determination! Parent partnership is warmly encouraged to discuss supportive growth strategies.`,
    `{studentName} has faced challenges with perseverance. We are warmly committed to intensive support and encouragement.`,
    `{studentName} succeeded with effort! Extra lessons and warm support are warmly recommended for continued growth.`,
    `{studentName} achieved with determination! Warm action and continued support needed - we are here to help!`,
    `{studentName} succeeded with perseverance! Parent partnership is warmly encouraged to plan for exciting improvement.`,
    `{studentName} passed with effort! Warm intervention and support are welcomed. We firmly believe in you!`,
    `{studentName} succeeded despite challenges! Extra lessons are warmly recommended for continued growth.`,
    `{studentName} has faced challenges with perseverance. Warm extra support is welcomed. Parent conference is warmly encouraged.`,
    `{studentName} achieved with effort! Warm support and guidance are warmly recommended for wonderful growth.`,
    `{studentName} succeeded with determination! Parent partnership is warmly encouraged to support learning.`,
    `{studentName} achieved with perseverance. Warm intervention and continued support are warmly recommended.`,
    `{studentName} passed with effort! Extra lessons and warm support strongly welcomed for growth.`,
    `{studentName} succeeded despite challenges! Parent partnership and warm support are warmly encouraged.`,
    `{studentName} achieved with determination! Warm action and support are welcomed for continued growth.`,
    `{studentName} succeeded with perseverance! Warm support is warmly recommended for success.`,
    `{studentName} passed with effort! Extra lessons are warmly recommended for wonderful growth.`,
    `{studentName} has faced challenges with determination. Parent conference is warmly encouraged for supportive planning.`,
    `{studentName} succeeded with perseverance! Warm intervention and support are warmly recommended.`,
    `{studentName} achieved with effort! Warm support is warmly recommended for continued improvement.`,
    `{studentName} succeeded with determination! Parent partnership is warmly encouraged to plan for exciting success.`,
    `{studentName} passed with perseverance! Extra lessons and warm support are warmly recommended.`,
    `{studentName} succeeded with effort! Warm action and encouragement warmly welcomed for growth.`,
    `{studentName} has faced challenges with perseverance. Warm comprehensive support and encouragement.`,
    `{studentName} achieved with determination! Parent conference and warm support are warmly welcomed.`,
    `{studentName} succeeded despite challenges! Extra lessons are warmly recommended for wonderful growth.`,
  ],

  veryPoor: [
    `{studentName} has faced significant academic challenges this term, achieving {averageScore}% average. Despite these difficulties, {pronoun} has persevered, and we are warmly committed to comprehensive support. Every child has unique potential and learns differently - we firmly believe in {possessive} capacity to grow and thrive. We warmly invite parents to partner with the school in creating a nurturing learning plan with intensive tutoring and patient encouragement. Together, we will help {objective} discover {possessive} strengths and succeed - improvement is absolutely possible.`,
    `{studentName} scored {averageScore}% average this term, showing perseverance through significant challenges. We are warmly dedicated to intensive support. We warmly recommend immediate patient intervention, extra lessons, and a parent-teacher conference to discuss how we can create a supportive environment where {pronoun} will thrive with confidence.`,
    `{studentName} has shown that comprehensive support is needed this term. We are warmly committed to intensive academic help. A comprehensive personalized learning plan and strong home-school partnership will create the nurturing environment where {pronoun} can flourish. We are firmly committed to {possessive} success - every step matters.`,
    `{studentName} has faced significant challenges this term! We are warmly committed to intensive support and encouragement. Extra tutoring, patient guidance, and parent partnership are warmly welcomed - we firmly believe in {possessive} potential!`,
    `{studentName} achieved despite significant challenges. We are warmly committed to comprehensive support. We warmly recommend extra lessons, academic support, and a parent meeting to discuss strategies for wonderful growth.`,
    `{studentName} has shown perseverance despite challenges. We are warmly committed to intervention and support. We are firmly committed to providing the help needed for {possessive} success.`,
    `{studentName} succeeded with significant effort! We are warmly committed to immediate support. Extra lessons and regular practice with patient encouragement are warmly recommended.`,
    `{studentName} achieved with perseverance despite challenges. We are warmly committed to intensive academic support. We firmly believe improvement is possible with warm patient help.`,
    `{studentName} succeeded despite significant challenges! We are warmly committed to comprehensive intervention. Parental partnership is warmly encouraged for continued growth.`,
    `{studentName} has faced significant challenges with perseverance. We are warmly committed to intensive help. We are firmly here to support {possessive} growth journey.`,
    `{studentName} achieved with determination despite challenges. We are warmly committed to extra support. A parent-teacher meeting is warmly encouraged for supportive planning.`,
    `{studentName} succeeded despite challenges! We are warmly committed to comprehensive intervention. We are firmly committed to helping {objective} thrive.`,
    `{studentName} has shown perseverance through challenges. We are warmly committed to urgent academic support. We firmly believe in {possessive} ability to grow.`,
    `{studentName} achieved with significant effort! We are warmly committed to immediate intervention. Extra tutoring is warmly recommended for wonderful growth.`,
    `{studentName} succeeded despite challenges. We are warmly committed to extra support. Parents are warmly encouraged to seek continued help.`,
    `{studentName} has shown determination through challenges. We are warmly committed to comprehensive support. Remedial classes are warmly recommended for growth.`,
    `{studentName} achieved with perseverance! We are warmly committed to intensive intervention. We firmly believe in {possessive} wonderful potential.`,
    `{studentName} has faced challenges with perseverance. We are warmly committed to comprehensive support. We are firmly here to help {objective} thrive and succeed.`,
    `{studentName} succeeded despite significant challenges. We are warmly committed to urgent intervention. Extra support is warmly recommended for growth.`,
    `{studentName} achieved with effort! We are warmly committed to extra lessons. We are firmly committed to {possessive} continued success.`,
    `{studentName} succeeded despite challenges. We are warmly committed to immediate support. Parent partnership is warmly encouraged.`,
    `{studentName} has shown perseverance. We are warmly committed to intensive intervention. We firmly believe in {possessive} ability to grow with support.`,
    `{studentName} achieved with determination despite challenges! We are warmly committed to urgent support. Parents are warmly encouraged to work with the school.`,
    `{studentName} succeeded despite challenges! We are warmly committed to comprehensive intervention. We are firmly here to help {objective} thrive.`,
    `{studentName} has faced challenges with perseverance. We are warmly committed to immediate support. Extra lessons are warmly recommended for wonderful growth.`,
    `{studentName} achieved with significant effort. We are warmly committed to intensive help. We are firmly committed to {possessive} continued success.`,
    `{studentName} succeeded despite challenges! We are warmly committed to comprehensive support. Extra tutoring is warmly recommended for exciting growth.`,
    `{studentName} has shown determination through challenges. We are warmly committed to urgent intervention. We firmly believe wonderful improvement is possible.`,
    `{studentName} achieved despite significant challenges. We are warmly committed to extra support. Parental involvement is warmly encouraged for growth.`,
    `{studentName} succeeded with perseverance! We are warmly committed to major intervention. We are firmly committed to helping {objective} thrive and succeed.`,
    `{studentName} has faced challenges with determination! We are warmly committed to extra support. Parents are warmly encouraged to seek continued help.`,
  ],
}